theme: jekyll-theme-minimal
title: Baatchit - Your Personal Health Assistant
description: A modern health management app that helps you keep track of your medical records, appointments, and prescriptions.
baseurl: "/Baatchitapp"
url: "https://baatchitapp.github.io" 